main: "jp.jyn.jumphome.JumpHome"
name: "JumpHome"
version: "${project.version}"
website: "https://github.com/HimaJyun/JumpHome"
author: "HimaJyun( https://jyn.jp/ )"
description: "home, spawn, sethome for Bukkit"
